#!/usr/bin/env bash

ENV=$1

export PYTHONPATH=$PWD/..
../bin/codenode-admin init -name $ENV -test
rm $ENV/data/codenode.db
cd $ENV
django-admin.py syncdb --pythonpath=$PWD --settings="frontend.settings"

